### ISSUE TITLE
Http Request spans using RestSharp are not captured

### ISSUE THREAD

**Issue by feinoujc** [DataDog/dd-trace-dotnet#869] opened 2020-08-18 14:06 UTC
**Describe the bug**
We have observed that any http requests to an api that use RestSharp as the underlying library are not captured in DataDog APM

**To Reproduce**
1. Start an automatic transaction/span where a RestSharp async request is made (asp.net request for example)
2. View trace in APM
3. Note that there is no http client span created

**Expected behavior**

An http client span is created for all the http requests

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode:  automatic with msi installer
- Tracer version: 1.19.1
- OS: Windows Server 2019
- CLR: .NET Framework 4.8

**Additional context**

RestSharp looks like it is using the old APM style (Begin/End) asynchronous programming for HttpWebRequest https://github.com/restsharp/RestSharp/blob/b48aee4411a65d93f67a8ea175d9cb342d56e833/src/RestSharp/Http.Async.cs

So one possible reason is that these are not instrumented currently

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\dotnet-profiler.log
Linux: /var/log/datadog/dotnet/dotnet-profiler.log
--!>

**Comment by kevingosse** [comment] 2020-08-19 11:22
Hello,

Your analysis seems correct. We currently don't instrument the Begin/End methods of HttpWebRequest, which explains why we miss those spans from RestSharp.

**Comment by macrogreg** [comment] 2020-10-14 22:48
This is a duplicate of https://github.com/DataDog/dd-trace-dotnet/issues/701
Please reopen if you feel that this is not the case.

**Closed by macrogreg** 2020-10-14 22:48 UTC
Labels: area:integrations, type:new-feature
