### ISSUE TITLE
Large traces reach payload limit

### ISSUE THREAD

**Issue by gc-dev1** [DataDog/dd-trace-dotnet#1002] opened 2020-10-28 16:55 UTC
**Describe the bug**
While running longer (up to 12 hours) .NET applications (multithreaded) and creating lots of traces.
The trace log catches this error and all traces get lost:
```
Cannot decode v0.4 traces payload: read limit reached
```

**Expected behavior**
Make sure the traces won't get dropped. Send them chunked?
Probably solved in trace rb?
https://github.com/DataDog/dd-trace-rb/issues/818

**Runtime environment:**
- Instrumentation mode: automatic + manual
- Tracer version: 1.19.1
- OS: Windows Server Datacenter 2019
- CLR: .NET Framework 4.8

**Comment by zacharycmontoya** [comment] 2020-10-28 19:41
Hi @gc-dev1 thanks for reporting this issue and the several issues you've filed in the past to help improve the product. Can you confirm what version of the Datadog Agent you are sending traces to? In [Datadog Agent 7.21.0](https://github.com/DataDog/datadog-agent/releases/tag/7.21.0) the maximum payload size of incoming traces was increased to 50 MB, which may solve the problem in the short-term.

We are also making plans to better split payloads sent to the agent so this does not happen, but until that work is finished perhaps the suggested upgrade may work for you.

**Comment by gc-dev1** [comment] 2020-10-28 20:34
Hi @zacharycmontoya thank you for your help.
On this host we are running Datadog Agent 7.22.0 already.

Just a note on the side:
I also had to adjust the maximum allowed traces per second. Since I had no idea that launching 20-30 applications simultaneously (after deployment) can cause quite a few traces in a short amount of time. Somewhat arround 7000-8000 traces within a second for like 5-10 seconds. Maybe someone has an idea to get arround spikes - without setting limits generally too high.

Sounds like a plan. If you have any other suggestions just let me know.

All this tracing comes in really handy, especially if you have to work with applications you didn't write.
So thanks for building a tool likes this :)

**Comment by zacharycmontoya** [comment] 2020-10-29 16:06
Thanks for confirming the Datadog Agent version. To help us get further information can you open a [support ticket](mailto:support@datadoghq.com)? Please reference this GitHub issue and include logs from `%ProgramData%\Datadog .NET Tracer\log` so we can look through the case with full context.

I'm glad the tool is useful! And I'd like to return the thanks because filing issues like this helps us improve the product.

**Comment by macrogreg** [comment] 2020-10-29 23:45
Hi folks, 
This seems to be a duplicate of https://github.com/DataDog/dd-trace-dotnet/issues/259.
I will close this for now and make a note there about this copy. 

Please feel free to re-open and to add new info if you think that this is not actually a duplicate.

Thanks!

**Closed by macrogreg** 2020-10-29 23:45 UTC
Labels: area:tracer, priority:missing-traces
