### ISSUE TITLE
Datadog.Trace.ClrProfiler.Native

### ISSUE THREAD

**Issue by mrtristan** [DataDog/dd-trace-dotnet#3410] opened 2022-11-02 17:47 UTC
Running a full framework console app on windows server, tracer 2.18, agent 7.39.2.1

log is dumping this line and apm isn't working:
https://github.com/DataDog/dd-trace-dotnet/blob/dff77dd9b50f8a3dd6b5d35687aaaa617904d9a4/tracer/src/Datadog.Trace/ContinuousProfiler/ProfilerStatus.cs#L73

any clear indication as to what would cause this? same setup is working in another `env` with the same configuration and apm is working on this machine for other apps (mix of services, iis sites, console apps). Not sure if the root cause is `Failed to get the runtime-id from native: Unable to load DLL 'Datadog.Trace.ClrProfiler.Native'`

Relevant logs:
```
2022-11-02 17:37:26.839 +00:00 [INF] Using ApiWebRequestFactory for discovery transport.  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:26.909 +00:00 [INF] Using ApiWebRequestFactory for trace transport.  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:26.999 +00:00 [INF] Building automatic tracer  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.004 +00:00 [INF] Failed to get the runtime-id from native: Unable to load DLL 'Datadog.Trace.ClrProfiler.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.039 +00:00 [INF] Continuous Profiler is enabled.  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.044 +00:00 [WRN] No profiler related feature(s) will be enabled. Failed to retrieve profiler status native pointer. System.DllNotFoundException: Unable to load DLL 'Datadog.Profiler.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Datadog.Trace.ContinuousProfiler.NativeInterop.NativeMethods.GetProfilerStatusPointer()
   at Datadog.Trace.ContinuousProfiler.NativeInterop.GetProfilerStatusPointer()
   at Datadog.Trace.ContinuousProfiler.ProfilerStatus.EnsureNativeIsIntialized()
 { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.109 +00:00 [INF] Using ApiWebRequestFactory for telemetry transport.  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.110 +00:00 [INF] Using ApiWebRequestFactory for telemetry transport direct to intake.  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }
2022-11-02 17:37:27.374 +00:00 [INF] DATADOG TRACER CONFIGURATION - {"date":"2022-11-02T17:37:27.3620794+00:00","os_name":"Windows","os_version":"Microsoft Windows NT 6.2.9200.0","version":"2.18.0.0","platform":"x64","lang":".NET Framework","lang_version":"4.8","env":"prod","enabled":true,"service":"REDACTED_SERVICE_NAME","agent_url":"http://127.0.0.1:8126/","agent_transport":"Default","debug":false,"health_checks_enabled":false,"analytics_enabled":false,"sample_rate":null,"sampling_rules":null,"tags":[],"log_injection_enabled":true,"runtime_metrics_enabled":true,"disabled_integrations":[],"routetemplate_resourcenames_enabled":true,"routetemplate_expansion_enabled":false,"querystring_reporting_enabled":true,"obfuscation_querystring_regex_timout":200.0,"partialflush_enabled":false,"partialflush_minspans":500,"runtime_id":"7a8c630f-ff6a-4146-ba5c-69b24ce38936","agent_reachable":true,"agent_error":"","appsec_enabled":false,"appsec_trace_rate_limit":100,"appsec_rules_file_path":"(default)","appsec_libddwaf_version":"(none)","iast_enabled":false,"iast_deduplication_enabled":true,"iast_weak_hash_algorithms":"HMACMD5,MD5,HMACSHA1,SHA1","iast_weak_cipher_algorithms":"DES,TRIPLEDES,RC2","direct_logs_submission_enabled_integrations":[],"direct_logs_submission_enabled":false,"direct_logs_submission_error":"","exporter_settings_warning":["No transport configuration found, using default values"],"dd_trace_methods":"","activity_listener_enabled":false,"profiler_enabled":false,"code_hotspots_enabled":false,"wcf_obfuscation_enabled":true,"data_streams_enabled":false,"span_sampling_rules":null}  { MachineName: ".", Process: "[61536 REDACTED]", AppDomain: "[1 REDACTED.exe]", TracerVersion: "2.18.0.0" }```

**Comment by andrewlock** [comment] 2022-11-03 10:36
Hi @mrtristan,

This looks like an incorrect configuration for the application; one or more of the required environment variables appear to be incorrect. 

There are probably wo best courses of action:

1. Use the [diagnostic tool](https://docs.datadoghq.com/tracing/troubleshooting/dotnet_diagnostic_tool/) to try to work out what's going on. After downloading, you can check your process (process id `61536` in the above logs) using `dd-trace check process 61536`. That should tell you what the problem is with your environment variables. Best approach then is to uninstall the MSI (if that's what you're using), remove any remaining "incorrect" env variables, and reinstall the MSI
2. If that doesn't work, contact support at support@datadoghq.com - they can walk you through collecting all the details we need to figure out what the issue is. Please include a link to this issue when you contact them so we can link everything up!

Thanks!

**Comment by mrtristan** [comment] 2022-11-03 13:54
@andrewlock thanks! that's a very cool tool that i missed. i'll work on uninstalling/reinstalling the tracer and see if that helps. (it was the msi)

if it's of value to you, here's what i'm seeing out of that tool:

iis:
```
Inspecting worker process 67340
Target process is running with .NET Framework
DD_PROFILING_ENABLED is set.
The native loader library is not loaded into the process
The native tracer library is not loaded into the process
The continuous profiler library is not loaded into the process.
The continuous profiler needs the Datadog.Trace.ClrProfiler.Native module and the loader.conf file to work. Try
reinstalling the tracer in version 2.14+.
Tracer is not loaded into the process
The registry key SOFTWARE\Classes\Wow6432Node\CLSID\{846F5F1C-F9AE-4B07-969E-05C26BC060D8}\InprocServer32 is missing.
Make sure the tracer has been properly installed with the MSI.
```

cli app (i will fix that env var value):

```
Running checks on process 40636
Target process is running with .NET Framework
DD_PROFILING_ENABLED is set.
The native loader library is not loaded into the process
The native tracer library is not loaded into the process
The continuous profiler library is not loaded into the process.
The continuous profiler needs the Datadog.Trace.ClrProfiler.Native module and the loader.conf file to work. Try
reinstalling the tracer in version 2.14+.
Tracer is not loaded into the process
The environment variable COR_PROFILER should be set to '{846F5F1C-F9AE-4B07-969E-05C26BC060D8}' (current value:
'846F5F1C-F9AE-4B07-969E-05C26BC060D8')
The registry key SOFTWARE\Classes\Wow6432Node\CLSID\{846F5F1C-F9AE-4B07-969E-05C26BC060D8}\InprocServer32 is missing.
Make sure the tracer has been properly installed with the MSI.
```

**Comment by andrewlock** [comment] 2022-11-04 13:07
Yeah, that would explain it @mrtristan - The MSI sets those variables to the correct value, so I suggest uninstalling, _removing any leftover instances of the env vars_, and then reinstalling. Hopefully that solves it! 🙂

**Comment by mrtristan** [comment] 2022-11-04 13:47
thanks @andrewlock 

from what i can tell the cli app is the only one that had the env var issue (set at runtime) so i'd expect the iis app to be working.
i did uninstall / reinstall the tracer msi.

Two quick questions come to mind:
- i noticed some env vars expect `true` in the docs and others expect `1` - could getting that wrong cause issues?
- any issue with any of these being set at a machine level? (obviously some are mine and some as you mentioned are set automagically)
![image](https://user-images.githubusercontent.com/1546181/199986268-fbd862ac-21b6-44b4-a500-904e568fd4f2.png)

FYI I did open a support ticket 24 hours ago. pretty quiet there so far.

PS - I kept an eye out for you at Dash. Wanted to thank you for the great blog and everything you put out there for the dotnet community.

**Comment by andrewlock** [comment] 2022-11-04 14:11
> from what i can tell the cli app is the only one that had the env var issue (set at runtime) so i'd expect the iis app to be working.

The IIS one doesn't look right either, as the tracer is not loaded into the process. That definitely suggests there's something wrong there with the install to me. Make sure to stop and start iis as described in the docs after install

> i noticed some env vars expect true in the docs and others expect 1 - could getting that wrong cause issues?

It's generally not an issue, but `cor_enable_profiling` etc do need to be `1` I believe. For the datadog variables, we handle both

> any issue with any of these being set at a machine level? (obviously some are mine and some as you mentioned are set automagically)

No, that shouldn't be an issue

> Wanted to thank you for the great blog and everything you put out there for the dotnet community

Thanks, really appreciate it! 😃

**Comment by andrewlock** [comment] 2023-03-16 10:12
Hi @mrtristan, I hope you managed to resolve your install issues! Would be interested to know what the problem was if you got to the bottom of it. I'll close this issue for now, but feel free to reopen or create a new ticket if you have any more problems! Thanks

**Closed by andrewlock** 2023-03-16 10:12 UTC

**Comment by mrtristan** [comment] 2023-03-16 14:56
@andrewlock i _believe_ I identified that the issue was pertaining to some of the env vars being set by the running application instead of them being set by a calling process.

Don't remember the resolution for the IIS app. Could be similar. A bit hacky, but changing how the console app was invoked would be way too complicated as it's invoked many different ways from a job scheduling application so i injected a "wrapper" around it by moving all the code to another project and making the "wrapper" look like the original console app:

![image](https://user-images.githubusercontent.com/1546181/225621124-40fb19e8-3215-429d-8228-62968b043799.png)

thanks for the help back then

**Comment by andrewlock** [comment] 2023-03-16 16:09
> I identified that the issue was pertaining to some of the env vars being set by the running application instead of them being set by a calling process.

Ah, yes, that would totally make sense. We hook very early into the execution process (before the application starts executing your code) so by then it's too late to set the variables. Thanks for the update!
