### ISSUE TITLE
Dispose/Close/Finish does not wait trace to get flushed.

### ISSUE THREAD

**Issue by jinek** [DataDog/dd-trace-dotnet#777] opened 2020-07-01 23:48 UTC
**Describe the bug**
When calling on of the methods **Tracer.Dispose** or **Tracer.Close** or **Span.Finish** the expected behavior is data to be sent to agent. **Span.Finish** says in its documentation: "Record the end time of the span and flushes it to the backend. After the span has been finished all modifications will be ignored".

**To Reproduce**
1. Create simple .NET Console application
2. Install Datadog.Trace NUGET version 1.18
3. Write code to trace a span and don't delay application closing and run it:
```
        public static void Main(string[] args)
        {
            using (Scope scope = Tracer.Instance.StartActive("manual.fastshutdown"))
            {
                scope.Span.Type = SpanTypes.Custom;
                
            }
            
            //Thread.Sleep(10000); //uncomment this line to get trace into datadog
        }
```
4. Check datadog APM traces: there is no **manual.fastshutdown** trace in it.
5. uncomment commented line and run again
6. Check that trace **manual.fastshutdown** appeared in datadog

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGet package
- Tracer version: 1.18
- OS: Windows
- CLR: .NET Framework 4.8

**Comment by macrogreg** [comment] 2020-10-01 02:51
Hi @jinek ,

Thank you for the submission! You bring up a good point.
* Spans a batched before being sent to the back-end. We will adjust the docs to be clearer.
* When you dispose the whole tracer, we may be able to wait until the flush is completed. We will investigate this. Can you please share some information about your scenario so that we understand the constraints?

**Comment by jinek** [comment] 2020-11-03 20:31
@macrogreg The scenario is that one in the code. 
We probably loose last traces if they came right before application exit. 
I believe datadog "batch sender" should also handle **Application.ApplicationExit** or **AppDomain.CurrentDomain.ProcessExit** and probably **AppDomain.CurrentDomain.DomainUnload** (if Datadog instruments all domains) or similar. This way Datadog could delay the quiting process until it flashes the data. Or something like that.

**Comment by kevingosse** [comment] 2020-11-12 16:41
I could not reproduce the issue with 1.20.0. 
We do listen to DomainUnload/ApplicationExit events, so in theory it should be alright:

https://github.com/DataDog/dd-trace-dotnet/blob/v1.20.0/src/Datadog.Trace/Tracer.cs#L149-L150

**Comment by kehigginbotham** [comment] 2021-06-30 19:47
I am also experiencing this issue, but putting the Thread to sleep does not force the Tracer to flush.  Our app is a desktop application, so we are using a remote DataDog Agent.

**Comment by kehigginbotham** [comment] 2021-06-30 20:19
I have discovered a viable work-around for my use case.

Traces are flushed if the flow of control exits the Scope's scope gracefully.  In the event of an ApplicationExit or other event initiating shutdown, the active Scope is not flushed.  By adding the (VB.NET) code below in my ApplicationExit handler, I am able to force the active Scope to flush.

`If Tracer.Instance.ActiveScope IsNot Nothing
    Tracer.Instance.ActiveScope.Dispose()
End If`

**Comment by kevingosse** [comment] 2021-09-30 16:23
I am closing this issue.

For future reference:
- When the process exits gracefully, the tracer should be able to flush the pending traces. If not, this is the bug, please open a issue to report it
- When the process is about to exit brutally (threads being aborted for instance), you can first call `Tracer.Instance.ForceFlushAsync()` to avoid losing the pending traces

**Closed by kevingosse** 2021-09-30 16:23 UTC
Labels: type:bug, area:tracer, area:docs, status:needs-investigation
