### ISSUE TITLE
Missing certain Runtime Metrics

### ISSUE THREAD

**Issue by jeid64** [DataDog/dd-trace-dotnet#3373] opened 2022-10-19 17:42 UTC
**Describe the bug**
https://docs.datadoghq.com/tracing/metrics/runtime_metrics/dotnet/#automatic-configuration Lists several metrics that aren't actually produced by the tracer. We do not see the runtime.dotnet.aspnetcore.connections.current emitted by the tracer when we have runtime metrics turned on, we are running on .NET Core 3.1. 

We took a look at the code and saw that https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs#L58 on this line the tracer will send the metric if it exists, but nothing in the codebase actually ticks the metric. 

We see the Request count metric get ticked here https://github.com/DataDog/dd-trace-dotnet/blob/1680ae614a4c2f313666c8544c240be76d1700d6/profiler/src/Demos/Shared/RuntimeMetrics/RuntimeProvider.cs#L42 and the request count metric works. The request count metric is the only metric in the Dictionary at https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeEventListener.cs#L58 that works.

**To Reproduce**
Enable runtime metrics
Look for runtime.dotnet.aspnetcore.connections.current and see it not emitted

**Expected behavior**
All of the metrics listed in the doc and dictionary be emitted. 

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGET package
- Tracer version: 2.17.0
- OS: Linux
- CLR: .NET Core 3.1

**Comment by andrewlock** [comment] 2023-03-16 11:10
Hi @jeid64,

Sorry for the delay getting back to you. The problem is that .NET Core 3.1 does not expose these counters. If I enable runtime metrics (`DD_RUNTIME_METRICS_ENABLED=1`) and enable debug logging (`DD_TRACE_DEBUG=1`) the logs describe the metrics sent. For .NET Core 3.1 you see something like the following:

.NET Core 3.1
```
Sent the following metrics to the DD agent: runtime.dotnet.threads.contention_time, runtime.dotnet.threads.contention_count, runtime.dotnet.threads.workers_count
Sent the following metrics to the DD agent: runtime.dotnet.threads.count, runtime.dotnet.mem.committed, runtime.dotnet.cpu.user, runtime.dotnet.cpu.system, runtime.dotnet.cpu.percent
Sent the following metrics to the DD agent: runtime.dotnet.exceptions.count
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.total
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.current
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.failed
```

whereas For .NET 7, the metrics look something like this:

.NET 7
```diff
Sent the following metrics to the DD agent: runtime.dotnet.threads.contention_time, runtime.dotnet.threads.contention_count, runtime.dotnet.threads.workers_count
Sent the following metrics to the DD agent: runtime.dotnet.threads.count, runtime.dotnet.mem.committed, runtime.dotnet.cpu.user, runtime.dotnet.cpu.system, runtime.dotnet.cpu.percent
Sent the following metrics to the DD agent: runtime.dotnet.exceptions.count
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.total
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.current
Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.failed
+ Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.connections.total
+ Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.connections.current
+ Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.connections.queue_length
+ Sent the following metrics to the DD agent: runtime.dotnet.aspnetcore.requests.queue_length
```

(I have omitted the periodic `gc` metrics for brevity)

For .NET Core/.NET 5+ we use the event counters provided by the underlying frameworks. As you can see from [this doc](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters), the `current-connections` counter is only available in .NET 5+ which is why you don't see this in your application.

I've created a PR to update the documentation to make this clearer, but hopefully that explains it. I'll close the issue for now, but feel free to re-open or create a new issue if I'm not clear or you have further questions. Thanks!

**Closed by andrewlock** 2023-03-16 11:10 UTC
