### ISSUE TITLE
Item has already been added. Key in dictionary: "Datadog.Trace.ClrProfiler.Managed.Loader..." Key being added: ...

### ISSUE THREAD

**Issue by StefDigi** [DataDog/dd-trace-dotnet#659] opened 2020-02-25 09:22 UTC
**Describe the bug**
When i activate the .net Tracer on my productions erver, i'm facing an issue with a IIS site calling another IIS Site on the same server.
The 2nd IIS site service is totally KO due to the follinwg error.

**To Reproduce**
Each time the 2nd IIS site is called.

**Expected behavior**
Not having this issue ^^

**Traces**
2020-02-24 10:23:01.748 +01:00 [ERR] An error occurred while sending traces to the agent at System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n...a pu ..tre ..tablie car l...ordinateur cible l...a express..ment refus..e 127.0.0.1:8126

Error on the application:
![Erreur Telefi](https://user-images.githubusercontent.com/61453858/75233159-b4f86c80-57b8-11ea-9e2e-0bddd867d9d6.PNG)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.13.0
- OS: Windows Server 2012 R2 Standard
- CLR: .NET Framework 4.6

Thanks for your help !

**Comment by lucaspimentel** [comment] 2020-02-25 14:52
The error "An element with the same key already exists in the dictionary" is a known issue in 1.13.0 and was fixed in [1.13.2](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.13.2). Please update the .NET Tracer to the latest version.

**Comment by lucaspimentel** [comment] 2020-02-25 14:54
Actually, I was thinking of [this issue](https://github.com/DataDog/dd-trace-dotnet/issues/653). This one looks like something different.

**Comment by StefDigi** [comment] 2020-02-25 15:17
Indeed, it's not the same issue as mine.

**Comment by lucaspimentel** [comment] 2020-02-25 15:21
Note to self: translation of error message in the screenshot to English:
```
Item has already been added. Key in dictionary: ... Key being added: ...
```

**Comment by lucaspimentel** [comment] 2020-02-25 15:29
@StefDigi: there are two different errors in this issue. The first is:
```
An error occurred while sending traces to the agent - target machine actively refused it 127.0.0.1:8126
```
To enable APM, the Datadog Agent is required in addition to the .NET Tracer. By default the Agent listens for traces on `localhost:8126` and the Tracer sends traces there. Please follow the instructions [in these docs](https://docs.datadoghq.com/tracing/send_traces/) to set up the Agent.

The second error message is the one in the screenshot:
```
Item has already been added. Key in dictionary: ... Key being added: ...
```

I am going to edit this issue and make it about this second issue only. If you need help setting up the Agent, please [contact our support team](https://www.datadoghq.com/support/).

**Comment by lucaspimentel** [comment] 2020-02-26 19:03
@StefDigi: Do you have a full stack trace for the error above? We're trying to determine where the code is that adds items into a dictionary using key `Datadog.Trace.ClrProfiler.Managed.Loader, Version=1.13.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb` .

Also, can you confirm if this still happens with [version 1.13.2](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.13.2) of the Tracer?

**Comment by bobuva** [comment] 2020-04-02 20:17
@StefDigi Can you confirm whether or not you installed version 1.13.2, or a later version, and whether it fixed the issue? If it did not fix it, can you send the stack trace associated with the `Item has already been added.` error?

**Comment by StefDigi** [comment] 2020-04-03 12:43
I managed to solve this issue by deleting the Datadog folder in this folder:
C:\Windows\Microsoft.NET\assembly\GAC_MSIL
The uninstall process and the server reboot has not deleted the remaining Datadog folder which resulted to an application crash.

**Comment by StefDigi** [comment] 2020-04-03 12:44
Using the 1.13.0.0 version of the tracer didn't solved my issue.

**Comment by lucaspimentel** [comment] 2020-04-06 15:50
@StefDigi: We haven't reproduced your exact issue (we need more details, like a stack trace, to try to reproduce your issue), but it sounds related to a race condition. We fixed one specific race condition in release 1.13.2 (meaning that 1.13.0 which you tested still had this issue). Have you tried a newer version of the tracer? The latest release as of this writing is [1.16.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.16.0).

**Comment by andrewsouthard1** [comment] 2020-04-12 19:10
Hey @StefDigi - would be great to understand if you still see this issue in the latest version of the tracer 1.16.0.

**Comment by lucaspimentel** [comment] 2020-04-14 16:34
@StefDigi: it seems like you were able to resolve this on your side. I'm closing the issue since we don't have enough information to reproduce it. Feel free to create a new one if needed. Thanks!

**Closed by lucaspimentel** 2020-04-14 16:34 UTC
Labels: priority:high, status:cannot-reproduce, type:bug
