### ISSUE TITLE
Increased CPU / Mem Usage

### ISSUE THREAD

**Issue by ffandreassoroko** [DataDog/dd-trace-dotnet#445] opened 2019-07-15 07:10 UTC
**Describe the bug**
After updating from 1.2 to 1.4.1 / 1.5 we noticed on all service a higher cpu / mem usage and one of our services ( the oldest one ) had the biggest impacts 

**Screenshots**
here is a mem screenshot,
after updating ( 1. ) we noticed 70-80% cpu usage (2 containers, so 20-40% per container), thats the point we killed the container and restarted them ( 2. ) then we waited and triggerd a rebuild ( thought maybe a broken container ) 3.  
![{FCBE5A82-C191-4765-8090-C2F5F33392FD} png](https://user-images.githubusercontent.com/47380084/61199741-4f4ee880-a6df-11e9-9a36-8054e5687446.jpg)
cpu / mem overview  
![{C8FE9BC6-1C60-4849-8E0B-6020FC91D502} png](https://user-images.githubusercontent.com/47380084/61199824-9ccb5580-a6df-11e9-96f2-7cff002b70ef.jpg)

cpu usage in sum  after new the containers comes a live 
![{855457DF-17E5-4D66-B08C-826FDA9BDD8A} png](https://user-images.githubusercontent.com/47380084/61199835-ab197180-a6df-11e9-927e-207088eb5fb7.jpg)

another thing we noticed a that the spans are totaly wrong connected ( and maybe not disposed ? ) a single trace had 1.8k spans, default is 2-4 - for this service totaly wrong
![{8B24B202-9F9A-4755-B0A8-84E3B22217D8} png](https://user-images.githubusercontent.com/47380084/61199857-c5534f80-a6df-11e9-8aad-ec52c204ef0b.jpg)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- OS: Linux / Docker image ( microsoft/dotnet:2.1-runtime-deps-stretch-slim )
- CLR: .Net Core 2.1

**Additional context**
currently we downgraded back to 1.2 and dont have the time to do a step by step upgrade to find which version produces this behavior

**Comment by colin-higgins** [comment] 2019-07-15 15:04
Thank you for reporting this @ffandreassoroko 
We will look into this and update you with any questions or progress we make.

**Comment by lucaspimentel** [comment] 2019-07-15 16:56
@ffandreassoroko: I suspect that the lower performance and increased resource usage is caused by a Linux-only change we made in [release 1.3](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.3.0).

The TL;DR is that a bug in .NET Core's JIT compiler on some platforms caused the AutoMapper library to throw exceptions. For more details you can see https://github.com/DataDog/dd-trace-dotnet/issues/302#issuecomment-496654196 and #363. To avoid crashing users' applications, our workaround was to disable all JIT compiler optimizations by default when the profiler is attached on Linux.

To disable the workaround (and re-enabled JIT optimizations), you can set the environment variable
```
DD_CLR_DISABLE_OPTIMIZATIONS=false
```

Note that the latest .NET Core releases (2.1.12 and 2.2.6 from July 9) fix the compiler bug, so this workaround will not be needed going forwards. See https://github.com/dotnet/coreclr/issues/24676. We will disable the workaround by default in a future version of our .NET Tracer.

----

> a single trace had 1.8k spans, default is 2-4 - for this service

We will investigate further, but at first glance my guess is that this is an unrelated issue.

**Comment by ffandreassoroko** [comment] 2019-07-16 12:49
> Note that the latest .NET Core releases (2.1.12 and 2.2.6 from July 9) fix the compiler bug, so this workaround will not be needed going forwards.

we did the update to **2.2.6** and updated again DD to **1.4.1 / 1.5**  also 
**ENV DD_CLR_DISABLE_OPTIMIZATIONS false** was set

![image](https://user-images.githubusercontent.com/47380084/61295652-d633bc00-a7d8-11e9-9d5f-12e5de724ae1.png)

**Comment by lucaspimentel** [comment] 2019-07-16 13:24
@ffandreassoroko: I'm not sure what I'm looking at in those graphs. Was there no improvement with `DD_CLR_DISABLE_OPTIMIZATIONS=false`?

**Comment by ffandreassoroko** [comment] 2019-07-16 14:18
>  I'm not sure what I'm looking at in those graphs.

sorry!
1. graph -> **request / per second**, normaly looks like this 
![image](https://user-images.githubusercontent.com/47380084/61301639-9246b400-a7e4-11e9-9d2a-7a836e86a21b.png) 
 ( was only as information that something creepy happens and the rate per seconds also drops )
2. graph -> **cpu usage** for one of our services with the datadog lib update ( 2 lines -> 2 container ), both have a cpu usage between 50-100% cpu usage after updating
3. graph -> **memory usage** the 2 lines before are before the update, as you can see normaly it its nearly by 100mb memory usage. the other 2 lines after updating

> Was there no improvement with DD_CLR_DISABLE_OPTIMIZATIONS=false

did not saw any improvements

**Comment by lucaspimentel** [comment] 2019-07-16 16:23
> did not saw any improvements

Thanks for clarifying!

> I suspect that the lower performance and increased resource usage is caused by a Linux-only change we made in release 1.3.

Looks like my suspicion was wrong, then.

> currently we downgraded back to 1.2 and dont have the time to do a step by step upgrade to find which version produces this behavior

If you do find the time to do this, it would really help us to narrow it down. Meanwhile, we will look into other recent changes made since 1.2.

**Comment by ffandreassoroko** [comment] 2019-07-17 12:00
all test with `ENV DD_CLR_DISABLE_OPTIMIZATIONS false`

**normal setup:**
> .NET: 2.2.1/2.2.6
> Datadog.Trace: 1.2
> Datadog.Trace.ClrProfiler.Managed: 1.2

- no problems

**first test:**
> .NET: 2.2.6
> Datadog.Trace: 1.2
> Datadog.Trace.ClrProfiler.Managed: 1.3.1

- mem usage okay
- spans okay
- cpu usage increased -> 5-10% 

**second test:**
> .NET: 2.2.6
> Datadog.Trace: 1.4.1
> Datadog.Trace.ClrProfiler.Managed: 1.3.1

- no changes, same behaviour like **first test**


**thrid test:**
> .NET: 2.2.6
> Datadog.Trace: 1.4.1
> Datadog.Trace.ClrProfiler.Managed: 1.4.1

- no changes, same behaviour like **first test**

**fourth test:**
> .NET: 2.2.6
> Datadog.Trace: 1.4.1
> Datadog.Trace.ClrProfiler.Managed: 1.5.0

- spans not correct connected
- high cpu usage
- mem leak

**Comment by yohanb** [comment] 2019-07-24 15:02
Hi,
piggybacking on the discussion to say that I'm having the same issue in my production environment.  Our current setup:

> .NET: 2.2.203
> Datadog.Trace: 1.2.0
> Datadog.Trace.ClrProfiler.Managed: 1.3.1

We're seeing a steady increase in heap memory usage related to instances of `Datadog.Trace.Span` and `Datadog.Trace.SpanContext`.  For example, the number of instances in our memory dump have tripled in about 10 hours.
We've made sure they are correctly wrapped in `usings` for GC.  Looking through the code, we noticed this (`Datadog.Trace.Scope`):
```
        public void Dispose()
        {
            try
            {
                Close();
            }
            catch
            {
                // Ignore disposal exceptions here...
                // TODO: Log? only in test/debug? How should Close() concerns be handled (i.e. independent?)
            }
        }
```
This could lead to some missed garbage collection.  We'll try debugging and see if we can replicate this issue and potentially create a pull request if we find anything.

**Comment by lucaspimentel** [comment] 2019-07-30 14:14
@ffandreassoroko: We introduced a regression in the ASP.NET Core MVC integration in v1.5.0. We reverted this change in [v1.6.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.6.0), so I'm closing this issue. Thanks for your help!

**Closed by lucaspimentel** 2019-07-30 14:14 UTC
Labels: status:needs-investigation, type:performance

**Comment by lucaspimentel** [comment] 2019-08-05 15:00
@yohanb: This issue #445 was about a regression in Tracer 1.5 where we were accidentally aggregating multiple traces into one, potentially causing hundreds or thousands of traces to stay in memory because being flushed to the Agent.

If you still have the memory issues you mentioned, can you create a new issue for that? Thanks.
