### ISSUE TITLE
Increased CPU usage after upgrading to 2.11.0

### ISSUE THREAD

**Issue by lukashovancik** [DataDog/dd-trace-dotnet#2997] opened 2022-07-20 14:31 UTC
**Describe the bug**
After I have upgraded datadog from version 2.4.2 to version 2.11.0 I have noticed after 3 weeks significant increase of CPU usage by my service. After downgrading to version 2.4.2 the problem disappeared . I have managed to do experiment with version 2.9.0 and the behaviour was the same as 2.4.2. So the problem might be 2.10.0 or 2.11.0. 

**Screenshots**

<img width="610" alt="Screenshot 2022-07-20 at 17 29 46" src="https://user-images.githubusercontent.com/11795945/180023128-bb61f927-2593-4d57-af45-b277ccc840c9.png">

<img width="880" alt="Screenshot 2022-07-20 at 16 23 03" src="https://user-images.githubusercontent.com/11795945/180007574-e806ee95-56c6-4987-9985-cc21e77a656c.png">

**Runtime environment (please complete the following information):**
- Docker
- Tracer version: 2.11.0
- OS: Linux (Debian 11)
- Net 6
- ~~Nuget~~

**Comment by pierotibou** [comment] 2022-07-21 07:15
Hello @lukashovancik , thanks for reporting the issue. We'll look on our end to see if we reproduce easily.

Regarding your setup, when you specify `Nuget`, do you mean you use custom instrumentation (ie `Datadog.Trace`), or automatic instrumentation using the beta nuget `Datadog.Monitoring.Distribution` ? In the first case, would you happen to have installed the tracer on the server as well for automatic instrumentation, and in which case, what version are you using?

Also, as you mentioned, CPU and Exception profiler, have you enabled them by setting `DD_PROFILING_ENABLED` ?

Thanks

**Comment by lukashovancik** [comment] 2022-07-21 09:41
Hello,

actually it's not a nuget package but Datadog .Net tracer installed on Debian . Yes we do have profiling enabled. 

```shell
ENV DD_PROFILING_ENABLED=true
ENV DD_RUNTIME_METRICS_ENABLED=true

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json
ENV DD_DOTNET_TRACER_HOME=/opt/datadog
`
Thank you.

**Comment by lukashovancik** [comment] 2022-07-21 09:51
`DD_PROFILING_ENABLED `  has been enabled also for `2.4.2`

**Comment by kevingosse** [comment] 2022-07-21 11:09
> `DD_PROFILING_ENABLED` has been enabled also for `2.4.2`

The continuous profiler for Linux was first made available with 2.10.0, so this setting would have no effect on previous versions.

It seems very likely that the CP is the cause of the overhead, but we never observed more than ~5% increase of CPU in our internal test environments. There's probably something specific about your setup that we're not testing.

Would it be possible for you to test two more scenarios?

- Set `DD_PROFILING_ENABLED` to `false`
- Set `DD_PROFILING_ENABLED` to `true` and `DD_PROFILING_CODEHOTSPOTS_ENABLED` to `false`

Meanwhile we're trying to repro the issue in our environments. Any information that you're willing to share about your app could help (number of CPU cores, memory usage, number of threads...).

Also, could you open a zendesk support ticket? It will make things easier if we need to share private information.

**Comment by lukashovancik** [comment] 2022-07-21 13:18
@kevingosse I can do both scenarios and open a support ticket with more informations about infrastructure.

**Comment by kevingosse** [comment] 2022-08-02 10:10
Just to circle back on this, what is the size of your containers? The profiler currently has a fixed overhead (about 200ms of CPU time per second on Linux, or 0.2 CPU). This is fine in most cases, but it can become very significant in small containers. For instance in a container with a limit of 1 CPU, that would be 20%. 

We are working on making that overhead adaptive in the coming versions, but for now that's something to consider when enabling the profiler.

**Comment by lukashovancik** [comment] 2022-08-03 19:19
Here are some results: (version 2.11.0)

-  `ENV DD_PROFILING_ENABLED=false`
<img width="643" alt="datadog-2 11 0_profiling_disabled" src="https://user-images.githubusercontent.com/11795945/182689234-e4cc4dd9-fb75-4631-bab7-f7bcf55e0fba.png">


-  `ENV DD_PROFILING_ENABLED=true`

<img width="635" alt="datadog-2 11 0_profiling_enabled" src="https://user-images.githubusercontent.com/11795945/182688838-653c5aea-cc62-49fb-83e6-66516fa94f1d.png">

@kevingosse Sorry for waiting but I didn't have time to come back to you.

**Comment by kevingosse** [comment] 2022-08-22 10:43
@lukashovancik for the thread spike issue, could it be that you didn't set the `LD_PRELOAD` environment variable? 

```
LD_PRELOAD=/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so
```

If it's omitted then it can cause some deadlocks, which would explain the thread spike. Starting with 2.13.0 we automatically disable the profiler if the variable is not properly set, to prevent this kind of issue.

**Comment by seanamos** [comment] 2022-09-20 20:57
Experiencing the same thing. The profiler is adding significant CPU usage to containers, in the range of 40-60%.

**Comment by lukashovancik** [comment] 2022-09-21 10:25
@kevingosse yes, I didn't set the LD_PRELOAD variable. So maybe that's the reason.

**Comment by gleocadie** [comment] 2023-02-20 14:41
@lukashovancik 
To circle back on this matter, how is it going currently ? which version are you using ?

**Comment by andrewlock** [comment] 2023-08-31 11:58
I'm going to close this one for now, feel free to reopen if you're still seeing issues with recent versions!

**Closed by andrewlock** 2023-08-31 11:58 UTC
Labels: type:performance, area:profiler
