### ISSUE TITLE
High CPU caused by many hanging calls to Datadog.Trace.Vendors.StatsdClient.Transport.NamedPipeTransport.Send when app not configured with `DD_` configs

### ISSUE THREAD

**Issue by dmmusil** [DataDog/dd-trace-dotnet#3882] opened 2023-03-11 22:32 UTC
**Describe the bug**
We use the Azure App Service extension. On the app services that exhibit this issue, we install the extension on both the production slot and a deployment slot. The production slot has the necessary configs for the extension to function and collect APM data. The deployment slot does not have these configs because we don't want to pollute data from the live slot with data from the idle deployment slot.  The only Datadog related config value that is defined in the deployment slot is `DD_VERSION`. 

For a couple months this has worked great. Recently, starting on Feb 25th as best I can tell, we've been seeing sporadic high CPU on the deployment slot only. A memory dump from the high CPU process on one instance shows 1678 threads are waiting on `Datadog.Trace.Vendors.StatsdClient.Transport.NamedPipeTransport.Send`. Another memory dump shows 2350 threads. 

As an experiment I added all the DD_ configs from the live slot to the deployment slot. As soon as I duplicate all the configs from the live slot into the deployment slot, the issue goes away.

**To Reproduce**
We haven't attempted to reproduce the behavior in a fresh app service yet.

**Expected behavior**
Datadog.Trace doesn't consume threads in a process that is not configured to communicate with the agent.

**Screenshots**
N/A

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic I think. We just add the Nuget package and configuration values via environment variables. We have a few custom spans, but most of our data is automatically captured.
- Tracer version: 2.18 and 2.26 both exhibit this issue
- OS: Windows (Azure App Service)
- CLR: .NET Framework 4.7.2

**Additional context**
Whenever we do a deployment we install the latest version of the App Service extension. We had been using Datadog.Trace v2.18 when this issue was first discovered. We have since upgraded to v2.26 to match the version of the extension but the issue persists.

Over the last couple weeks this issue has started to appear in multiple environments as new code reaches them. It's been hidden in the lower environments because we do frequent deployments that result in both slots being restarted which effectively clears this issue. Over the course of 6+ hours of idling the deployment slot will creep up to 50% CPU and then will reach 100% CPU before the process is killed.

I'm not sure that we need a fix since we can stop the deployment slot and mitigate the issue, but I wanted to report it in case it is something that is fixable and not an issue with our code. It's entirely possible that something changed in our app that caused this to start, but I wasn't able to find any smoking gun.

**Comment by andrewlock** [comment] 2023-03-15 10:24
Hi @dmmusil,

Thanks for raising this - it technically isn't an issue we were aware of, but it's not entirely unsurprising.

First of all, if you're not intending on sending data to Datadog on your deployment slot, is there any reason to have the AAS extension installed in your deployment slot? By running the extension, but _not_ providing the configuration, your app will be instrumented, and we will collect spans and metrics, and _try_ to send them to the agent. 

But if you don't provide the necessary config (i.e. DD_API_KEY), the agent and metrics collector (dogstastd) won't be started (as they can't send data to Datadog). There are several tasks in the tracer library that rely on contacting the agent for various reasons, and while these shouldn't _directly_ impact your app, they will obviously be taking up CPU and bandwidth in timing out etc.

There's clearly some work we can do to avoid this scenario when we're in an "unsafe tracing environment" (i.e. a mis-configured AAS website), but I think a simple fix for you would be to set `DD_TRACE_ENABLED=0` in your deployment slot. This will cause us to bail-out earlier, and should reduce the impact. 

However, you mention you're also using the Nuget package - if you're doing manual tracing using `Tracer.Instance` or are configuring the tracer in code then you will still be trying to contact the agent, which may mean the problem remains (and is a tricky one to solve unfortunately!). Can you confirm whether or not you're doing manual tracing?

> A memory dump from the high CPU process on one instance shows 1678 threads are waiting on Datadog.Trace.Vendors.StatsdClient.Transport.NamedPipeTransport.Send. Another memory dump shows 2350 threads.

It would be very interesting to be able to analyze these dumps ourselves - there's clearly something very awry here, which we should address regardless of the mitigations above! Would you be happy to share these memory dumps (privately obviously)?

**Comment by kevingosse** [comment] 2023-07-26 08:05
This issue should be fixed in 2.34.0. Don't hesitate to re-open the ticket if you keep seeing CPU spikes caused by `NamedPipeTransport` despite the fix.

**Closed by kevingosse** 2023-07-26 08:05 UTC
