### ISSUE TITLE
Trace buffer is full, dropping it.

### ISSUE THREAD

**Issue by andreas-soroko** [DataDog/dd-trace-dotnet#517] opened 2019-09-27 12:35 UTC
Hey, 
one of our services does many async stuff with kafka against s3 and we saw the messages in our logs, sometimes about 20k per min, we also noticed that the spans in DD completely disappear and it looks like the service is not there.

can i do anything to fix that ? 

Message: Trace buffer is full, dropping it.
Class: Datadog.Trace.Agent.AgentWriter
Method: CloseSpan

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.7.0
- OS: mcr.microsoft.com/dotnet/core/aspnet:2.2.6-stretch-slim
- CLR:  .NET Core 2.2.6

**Comment by rakker91** [comment] 2019-11-05 19:23
@ffandreassoroko ffandreassoroko, unfortunately, this is hard coded to 1000.  AgentWriter creates a new instance of AgentWriterBuffer that's hard coded to 1000.  After it hits that limit, it randomly overwrites traces in the buffer.

AgentWriter
`        private const int TraceBufferSize = 1000;

        private readonly AgentWriterBuffer<List<Span>> _tracesBuffer = new AgentWriterBuffer<List<Span>>(TraceBufferSize);
`

AgentWriterBuffer.cs
`
                if (_items.Count < _maxSize)
                {
                    _items.Add(item);
                    return true;
                }
                else
                {
                    _items[_random.Next(_items.Count)] = item;
                    return false;
                }
`

Datadog--this is a huge problem for us.  You say "Send us everything" but then put an arbitrary limit of 1000 per second.

We have data feeds doing 10 times that. . .  What's the solution?

**Comment by colin-higgins** [comment] 2019-11-05 20:13
You are correct, the arbitrary limit is not ideal.
We will prioritize making that limit configurable.
I will update you here soon.

**Comment by colin-higgins** [comment] 2019-12-31 16:20
For another update, this is a nuanced issue as we don't want to overwhelm the agent (responsible for stats and submitting traces to the backend) and also don't want to add too much to the network. 
This is more of a long term issue that we will need to develop a careful plan for.

**Comment by macrogreg** [comment] 2020-10-14 19:45
I think, this is a duplicate of https://github.com/DataDog/dd-trace-dotnet/issues/259
If not, please feel free to re-open.

**Comment by rakker91** [comment] 2020-10-14 19:54
This is most definitely NOT the same thing as 259.  259 is about payload size, where this one is about the number of messages that can be sent per second.  Not sure how to re-open . . .

**Comment by andreas-soroko** [comment] 2020-10-15 10:00
@macrogreg , no its not the same. See the answer from @rakker91.
I am also not able to reopen the issue.

**Comment by macrogreg** [comment] 2020-10-21 00:34
Hi @rakker91 , @andreas-soroko  reopened on your request.
However, the underlying reason for the limitation is the payload size. Many items result in a larger payload. :)

I called out this tracking item in https://github.com/DataDog/dd-trace-dotnet/issues/259 explicitly. I would prefer to use a single item to track this issue. Are you OK with continuing the conversation in https://github.com/DataDog/dd-trace-dotnet/issues/259 ?

**Comment by rakker91** [comment] 2020-10-21 14:28
I commented on the other item.  They are related, and this is probably a limit to prevent hitting the other issue, so as long as the limit is lifted once the other issue is addressed, we'll be good.

**Comment by macrogreg** [comment] 2020-10-23 22:14
Great. Thanks, @rakker91 .
I am closing this item then and we will continue tracking this issue using https://github.com/DataDog/dd-trace-dotnet/issues/259.

**Closed by macrogreg** 2020-10-23 22:14 UTC
Labels: area:reliability
