### ISSUE TITLE
Issue with release 2.17.0 for x64 systems

### ISSUE THREAD

**Issue by MJRomka** [DataDog/dd-trace-dotnet#3352] opened 2022-10-13 14:15 UTC
[datadog-dotnet-apm-2.17.0-x64.msi](https://github.com/DataDog/dd-trace-dotnet/releases/download/v2.17.0/datadog-dotnet-apm-2.17.0-x64.msi) cannot be properly downloaded and executed on Windows Server 2022. The access seem to be broken. See attachments
<img width="367" alt="Screenshot 2022-10-12 at 18 36 45" src="https://user-images.githubusercontent.com/3237392/195621310-339920e8-6128-478d-b3ca-60d9bd32435a.png">
<img width="488" alt="Screenshot 2022-10-13 at 13 03 44" src="https://user-images.githubusercontent.com/3237392/195621321-85966a6a-719a-4aef-b629-5d200e58c363.png">
<img width="373" alt="Screenshot 2022-10-13 at 17 14 11" src="https://user-images.githubusercontent.com/3237392/195621326-b073c05f-dfe4-4e15-97d2-47e1b55b3e08.png">
<img width="372" alt="Screenshot 2022-10-13 at 17 14 04" src="https://user-images.githubusercontent.com/3237392/195621330-8bfde3b6-dfb0-4aa6-ac8b-db52b5c67f44.png">

**Comment by MJRomka** [comment] 2022-10-14 05:56
Hi @andrewlock indeed, I can install the tracer on my local PC running on Win'11. But the fact that I can install any other version to our Server VM just fine except for 2.17.0-x64 makes me thinking the there is something wrong with this build.
Let's see if others have such a problem too. Thank you

**Comment by lucaspimentel** [comment] 2022-10-25 16:29
Closing this ticket as we can't reproduce and there are no action items on our side. @MJRomka feel free to re-open if you find any details that could help figure this out. Thanks!

**Closed by lucaspimentel** 2022-10-25 16:29 UTC
